my_car_site/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('list/', views.list, name='list'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete')
]

my_car_site/my_car_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('cars/', include('cars.urls')),
    path('admin/', admin.site.urls),
]

my_car_site/cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):

    #pk
    brand = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self):
        return f"Car Brand: {self.brand} the year is {self.year}"

my_car_site/cars/views.py
from django.shortcuts import render,redirect
from . import models
from django.urls import reverse

# Create your views here.
def list(request):
    all_cars = models.Car.objects.all()
    context = {'all_cars': all_cars}

    return render(request, 'cars/list.html', context=context)

def add(request):
    if request.POST:
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand=brand, year=year)
        return redirect(reverse('cars:list'))
    else:
        return render(request, 'cars/add.html')

def delete(request):
    if request.POST:
        pk = request.POST['pk']
        try:
            models.Car.objects.get(pk=pk).delete()
            return redirect(reverse('cars:list'))
        except:
            print('pk not found')
    else:
        return render(request, 'cars/delete.html')

my_car_site/cars/templates/cars/add.html
{% extends "base.html" %}

{% block content %}
<div class='container'>
    <h1>add.html</h1>
    <h2>Add a new car to the database:</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <div class='form-group'>
            <label for="brand">Brand:</label>
            <input class='form-control' type="text" id='brand' name='brand'>
        </div>
        <div 'form-group'> 
            <label for="year"> Year:</label>
            <input class='form-control' type="text" id='year' name='year'>
        </div>
        <input class='btn btn-primary' type="submit">
    </form>
</div>
{% endblock content %}

my_car_site/cars/templates/cars/delete.html
{% extends "base.html" %}

{% block content %}
<div class='container'>
    <h1>delete.html</h1>
    <h2>Add PK number to delete</h2>
    <form action="" method='POST'>
        {% csrf_token %}
        <div class='form-group'>
            <label for="pk">PK Number:</label>
            <input class='form-control' type="text" id='pk' name='pk'>
            <input type="submit" class='btn btn-primary'>
        </div>
    </form>
</div>
{% endblock content %}

my_car_site/cars/templates/cars/list.html
{% extends "base.html" %}



{% block content %}
<div class='container'>
    <h1>list.html</h1>
    <ul>
        {% for car in all_cars  %}
        <li>{{car}}</li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

my_car_site/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr"
    crossorigin="anonymous"
    />
    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
    crossorigin="anonymous"
    ></script>
    <title>Document</title>
</head>
<body>
    {% comment %} Navbar {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup"
        aria-expanded="false"
        aria-label="Toggle navigation"
        >
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-link" href="{% url 'cars:list'%}">List</a>
            <a class="nav-link" href="{% url 'cars:add'%}">Add</a>
            <a class="nav-link" href="{% url 'cars:delete'%}">Delete</a>
        </div>
        </div>
    </div>
    </nav>
    {% block content %} {% endblock content %}
</body>
</html>